### ISSUE TITLE
Organizacio 

### ISSUE THREAD

**Issue by silvermiguel96** [ultrasoft011/Portafolio#6]
Organizar toda la aplicacion y colocar por orden de modulos estos se deben separa por inicio y fin de cada modulo

Espacio
Espacio
Modulo nombre del modulo nicio 
Espacio
Espacio

Codigo

Espacio
Espacio
Modulo nombre del modulo Fin
Espacio
Espacio

Esto se debe aplicar tanto para HTML como CSS

**Comment by ultrasoft011** [comment]
Done: all fixed in Feature/fixed branch.
